import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Common/Header";

export const metadata: Metadata = {
  title: "Employee Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200 dark:bg-gray-800 dark:text-white">
        <Header />

        {children}
      </body>
    </html>
  );
}
